<template>
  <h1>O sorrow, my sorrow...</h1>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
   <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
  <food-item/>
</template>

<script></script>

<style>
  #app > div {
    border: dashed white 1px;
    display: inline-block;
    margin: 10px;
    padding: 10px;
    background-color: black;
  }
</style>